name: Busted

on: [push, pull_request]

jobs:

  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty"]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup dependencies
      run: |
        luarocks install --deps-only luacheck-dev-1.rockspec
        luarocks install busted
        luarocks install luacov-coveralls
    - name: Run busted test suite
      run: busted -c -v
    - name: Report test coverage
      if: success()
      continue-on-error: true
      run: luacov-coveralls -i luacheck -e .luarocks
      env:
        COVERALLS_REPO_TOKEN: ${{ github.token }}
