name: Versioning

on:
  release:
    types: [ created, published, edited ]

jobs:
  actions-tagger:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update release tags
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
